---
- name: Ensure configuration directories exist.
  file:
    path: "{{ item }}"
    state: directory
    follow: true
  with_flattened:
    - "{{ php_conf_paths }}"
    - "{{ php_extension_conf_paths }}"

- name: Place PHP configuration file in place.
  template:
    src: php.ini.j2
    dest: "{{ item }}/php.ini"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ php_conf_paths }}"
  notify: restart webserver
  when: php_use_managed_ini

- name: Create PHP error_log with appropriate permissions.
  file:
    path: "{{ php_error_log }}"
    state: touch
    owner: "{{ php_error_log_owner }}"
    group: "{{ php_error_log_group }}"
    mode: "{{ php_error_log_mode }}"
  when: php_error_log and php_error_log != "syslog" and php_error_log_owner and php_error_log_group
